server:
  address: 0.0.0.0
  port: ${PORT:8080}
  servlet:
    context-path: /

spring:
  application:
    name: moden-api

  config:
    import: optional:classpath:application-secret.yml

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  servlet:
    multipart:
      max-file-size: 20MB


# âœ… Swagger konfiguratsiyasi (springdoc)
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: alpha
    enabled: true
    path: /docs
    operations-sorter: method
    persist-authorization: true
  paths-to-match: /**
  default-produces-media-type: application/json

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.moden.modenapi: DEBUG
  output:
    ansi:
      enabled: ALWAYS

file:
  upload-dir: ./uploads
  base-url: http://localhost:${server.port}/uploads


app:
  admin:
    phone: "940223633"
    password: "root!234"

  jwt:
    secret: ${JWT_SECRET}
    access-expiration-ms: 86400000
    refresh-expiration-ms: 2592000000


firebase:
  credentials:
    base64: ${FIREBASE_SA_BASE64:}

cors:
  allowed-origins:
    - "http://localhost:5173"
    - "http://192.168.1.24:5173"
    - "http://localhost:8080"
    - "http://127.0.0.1:8080"
    - "http://122.37.246.79:7005"
    - "http://122.37.246.79:7006"
    - "http://122.37.246.79:7007"

