services:
  - type: web
    name: moden-api
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DB_URL
      - key: DB_USER
      - key: DB_PASS
      - key: JWT_SECRET
      - key: FIREBASE_SA_BASE64         # ⬅️ Firebase serviceAccount.json ni Base64 ko‘rinishidagi qiymat
      # - key: SPRING_PROFILES_ACTIVE   # (ixtiyoriy) dev/prod kabi profil kerak bo‘lsa
